### ISSUE TITLE
Add a contribution.md File

### ISSUE THREAD

**Issue by mdew192837** [BaReinhard/Hacktoberfest-Mathematics#15]
I think this could get very big very quickly, and we need an organized way of doing this. :)

**Comment by BaReinhard** [comment]
Agreed, I'm still debating what the best way it should be implemented. I am open to ideas. Currently thinking breakdown by language then the formula. Example:
/cpp/pythagoreantheorem/pythagoreantheorem.cpp.

Thoughts?

**Comment by BaReinhard** [comment]
Possibly, /language/math/formula/file
/cpp/geometry/pythagoreantheorem/pythagoreantheorem.cpp?

Or 
/math/formula/Lang/file

Not sure what feels more intuitive.

**Comment by Hiosdra** [comment]
First should be easier for programmers, I think
