### ISSUE TITLE
arithmetic operations in any language

### ISSUE THREAD

**Issue by tbhaxor** [BaReinhard/Hacktoberfest-Mathematics#181]
i am adding arithmetic operations like **digit_sums** , **cube_root**, **square_root** in _/Hacktoberfest-Mathematics/algebra/arithmetic_

i will code in `c++` , `csharp` and `python3`

**Comment by BaReinhard** [comment]
thank you! Going forward just feel free to make files at will and then create a pull request, no need to clutter the issues tab.
