### ISSUE TITLE
Looking for Maintainers to help merge pull requests

### ISSUE THREAD

**Issue by BaReinhard** [BaReinhard/Hacktoberfest-Mathematics#22]
Looking for maintainers to help merge pull request and insure proper implementations detailed in the CONTRIBUTIONS.md is followed. Also looking for people to help restructure the current files into the file structure described in the CONTRIBUTIONS.md file.

**Comment by mdew192837** [comment]
Can help merge @BaReinhard

**Comment by Hiosdra** [comment]
Can help too @BaReinhard

**Comment by BaReinhard** [comment]
I've added you as a collaborator.

**Comment by FilipeRamalho** [comment]
Can help maintaning and merging
