### ISSUE TITLE
New File Structure to be implemented

### ISSUE THREAD

**Issue by BaReinhard** [BaReinhard/Hacktoberfest-Mathematics#25]
**Implementing new File/Directory Structure**
* Try to keep things as modular as possible, the new file/directory structure should be: 
```
/area_of_mathematics/general_formula/formula/language/file
ex: /algebra/distance_formula/3d_distance_formula/java/3d_distance_formula.java
```

The new file structure has just been decided upon and all existing files need to be renamed/moved to the proper file directory.

**Comment by mdew192837** [comment]
I'll take care of this for now. We need to be more cautionary as we merge PRs...
