### ISSUE TITLE
Create geometric/trig function or formula in any lang

### ISSUE THREAD

**Issue by BaReinhard** [BaReinhard/Hacktoberfest-Mathematics#5]
Create a geometric or trigonometric formula/function in any language with the structure of:
/Lang/formula/filename

**Comment by bigblue92** [comment]
Hello, I'd like to pull on this

**Comment by BaReinhard** [comment]
@bigblue92 pull away! Just write a description of what it is you're pulling.

**Comment by nicolasmanic** [comment]
Hi, I would implement Pythagorean theorem in Java PR in a few minutes

**Comment by marvin08** [comment]
I would like to contribute.

**Comment by bigblue92** [comment]
I have a program written, but as soon as I requested a pull I went to pick up dinner for the family. I'll be back in 15! It is a Python Pythagorean Theorem.

**Comment by BaReinhard** [comment]
It's fine for this repo to have multiple of the same formulas, it serves as a resource for seeing different ways to implement the same functionality.

**Comment by marvin08** [comment]
I will not be able to contribute right now but will love to contribute to any other issue of your repo anytime later. Sorry for this.

**Comment by BaReinhard** [comment]
@marvin08 anytime and in any way is appreciated. Even just spreading the word on social media is helpful.

**Comment by marvin08** [comment]
Will try to contribute anytime later to some other issue of your repo.

**Comment by prakhar897** [comment]
Hey. I've written a program to find factorial of large numbers in java. I am still new to the fundamentals of github. Can anyone please help me.

**Comment by Garvit244** [comment]
Hey, I written snippet for finding area, length and angle made by arc in circle. Code is in Python language.

**Comment by Adroit11** [comment]
I have written a function for trigonometric in php.

**Comment by jpvg95** [comment]
Hey I have a bunch of geometry formulas and algorithms on Java. What exactly are you looking for?
I could pull tomorrow.

**Comment by naremuradyan** [comment]
#50 perimeter, area, volume formulas in objc
