### ISSUE TITLE
Create fitting (cool) SVG logo for repo website

### ISSUE THREAD

**Issue by BaReinhard** [BaReinhard/Hacktoberfest-Mathematics#64]
We need a cool logo created, for the repos website something with a little flare and definitely a math theme. You can see the site here:

https://bareinhard.github.io/Hacktoberfest-Mathematics

**Comment by BaReinhard** [comment]
This can also be a jpg, png, or gif. I'm not much of a designer so someone with that gift feel free to give it your touch.

**Comment by meganinj4** [comment]
i created those logos for you, it looks a little simple (and PNG) but it was the best that i could do fast

![sem titulo-6](https://user-images.githubusercontent.com/18127788/31107864-dc2788b2-a7cb-11e7-98ae-86a085735d3b.png)
![sem titulo-3](https://user-images.githubusercontent.com/18127788/31107865-dc283816-a7cb-11e7-9c5d-a4c2320cdd5c.png)
![sem titulo-4](https://user-images.githubusercontent.com/18127788/31107866-dc29f8ea-a7cb-11e7-95b7-31eb9b080748.png)
![sem titulo-5](https://user-images.githubusercontent.com/18127788/31107867-dc2ae822-a7cb-11e7-9929-0a860a5405d8.png)

**Comment by jndachenhaus** [comment]
![untitled-4](https://user-images.githubusercontent.com/13964975/31108294-6574eb88-a7c6-11e7-9215-3a1294e27f23.png)

**Comment by BaReinhard** [comment]
Create a pull request with a file in the root directory, name it logo.svg I'll merge it.

**Comment by mdew192837** [comment]
Closed per #80
